# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25c9e460b5962061f534602599ae95d12a5d63326e89a2b4e7d1c1a7b148d5af389ed85ab450ba9bdbd32deadf6c611a83ef47c3ccf6fea908913ae2e7b40dfd

test:
  secret_key_base: b5ee68cbf38fd99790891ccd93a41b3a186b8926981fbcc040febe8fbf1b84595fc500848382bd23439c5fd4f4a1f8588beda1f12f40db8f60f3cc05d9a19ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
